/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.toomuchzelda.sndminestom;

import net.minestom.server.MinecraftServer;

public class Main {
    
	MinecraftServer mcServer = MinecraftServer.init();
	
}
